FROM nginx:alpine

#copy static files vào thư mục nginx
COPY . /usr/share/nginx/html

#copy nginx config nếu có
#copy nginx.conf /etc/nginx/nginx.conf

#set quyền truy cập
RUN chown -R 755 /usr/share/nginx/html

#Expose port
EXPOSE 80
#Start nginx
CMD ["nginx", "-g", "daemon off;"]